title: Siddhartha Prasad
email: siddharthaDOTaDOTprasad@gmail.com
description: >-
  Personal website of Siddhartha Prasad
baseurl: "" # Leave blank for user/organization GitHub Pages
url: "https://www.siddharthaprasad.com" # Use your custom domain

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
