title: Siddhartha Prasad
email: siddharthaDOTaDOTprasad@gmail.com
description: >-
  Siddhartha Prasad's personal website.
baseurl: "" # Leave blank for user/organization GitHub Pages
url: "www.siddharthaprasad.com" # Use your custom domain

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
